export const thresholds = {
  Healthcare: {
    investimentoPD: { good: 0.1, medium: 0.05 },
    margemBruta: { good: 0.6, medium: 0.4 },
    margemEbitda: { good: 0.3, medium: 0.2 },
    margemLiquida: { good: 0.15, medium: 0.05 },
    roic: { good: 0.15, medium: 0.08 },
    roe: { good: 0.18, medium: 0.1 },
    pl: { good: 15, medium: 25 },
    ps: { good: 3, medium: 6 },
    debtToEbitda: { good: 2, medium: 3.5 },
    debtEquity: { good: 1, medium: 2, reverse: true }, // ✅
    liquidezCorrente: {
      good: 2.5,
      medium: 1.7,
      peso: 0.7,
      setorSensível: true,
    },
    cagrEps: { good: 0.15, medium: 0.08 },
    eps: { good: 3, medium: 1.5 },
    beta: { good: 1, medium: 1.2, neutralRange: [0.3, 0.6] },
    fcf: { good: 10000000, medium: 0 }, // ✅
    peg: { good: 1.0, medium: 1.5, reverse: true }, // ✅
    crescimentoReceita: { good: 0.15, medium: 0.05 }, // ✅
  },

  Technology: {
    'Crescimento Receita': { good: 20, medium: 10 },
    'CAGR EPS': { good: 15, medium: 8 },
    'EPS': { good: 0.1, medium: 0.01 },
    'Margem Bruta': { good: 60, medium: 40 },
    'Margem EBITDA': { good: 20, medium: 10 },
    'Margem Líquida': { good: 15, medium: 8 },
    'ROIC': { good: 10, medium: 5 },
    'ROE': { good: 15, medium: 8 },
    'P/L': { good: 20, medium: 30, reverse: true },
    'P/S': { good: 3, medium: 10, reverse: true },
    'PEG': { good: 1.0, medium: 1.5, reverse: true },
    'Dívida/EBITDA': { good: 2, medium: 4, reverse: true },
    'Liquidez Corrente': { good: 1.5, medium: 1.0 },
    'Cash Ratio': { good: 0.5, medium: 0.3 },
    'Beta': { good: 1.0, medium: 1.5, reverse: true },
  },
  utilities: {
    'pl': { min: 0, max: 20, reverse: true },
    'roe': { min: 10 },
    'margemEbitda': { min: 30 },
    'endividamento': { max: 70, reverse: true },
    'coberturaJuros': { min: 2 },
    'leveredDcf': { custom: 'aboveCurrentPrice' },
  },
  reits: {
    'dividendYield': { min: 6 },
    'pVpa': { max: 1.2, reverse: true },
    'ocupacao': { min: 90 },
    'capRate': { min: 6 },
    'coberturaJuros': { min: 1.5 },
    'dividaEbitda': { max: 3, reverse: true },
    'ffo': { min: 0 },
    'affo': { min: 0 },
    'pFfo': { max: 15, reverse: true },
    'ffoPayoutRatio': { min: 0, max: 90 },
    'dividendCagr5y': { min: 2 },
    'leveredDcf': { custom: 'aboveCurrentPrice' },
  },
  industrials: {
    'margemEbitda': { min: 15 },
    'roic': { min: 10 },
    'alavancagem': { max: 3, reverse: true },
    'coberturaJuros': { min: 2 },
    'liquidezCorrente': { min: 1.5 },
    'rotatividadeEstoques': { min: 5 },
    'pe': { min: 0, max: 20, reverse: true },
    'pb': { max: 3, reverse: true },
    'ps': { max: 2, reverse: true },
    'peg': { min: 0, max: 1.5, reverse: true },
    'dividendYield': { min: 2 },
    'beta': { min: 0.8, max: 1.5 },
    'giroAtivo': { min: 1 },
  },
  energy: {
    'pe': { min: 0, max: 18, reverse: true },
    'pb': { max: 2, reverse: true },
    'margemEbitda': { min: 25 },
    'dividaEbitda': { max: 2.5, reverse: true },
    'coberturaJuros': { min: 3 },
    'liquidezCorrente': { min: 1.2 },
    'dividendYield': { min: 3 },
    'roic': { min: 8 },
    'freeCashFlow': { min: 0 },
    'beta': { min: 0.6, max: 1.2 },
    'leveredDcf': { custom: 'aboveCurrentPrice' },
  },
  consumerDefensive: {
    'pe': { min: 0, max: 22, reverse: true },
    'pb': { max: 3, reverse: true },
    'ps': { max: 4, reverse: true },
    'roe': { min: 15 },
    'margemBruta': { min: 30 },
    'margemEbitda': { min: 15 },
    'receitaCagr3y': { min: 7 },
    'payoutRatio': { min: 0, max: 70 },
    'dividendYield': { min: 3 },
    'beta': { max: 1, reverse: true },
  },
  financials: {
    'roe': { min: 12 },
    'eficiencia': { max: 55, reverse: true },
    'indiceBasileia': { min: 11 },
    'alavancagem': { max: 10, reverse: true },
    'liquidezCorrente': { min: 1.2 },
    'inadimplencia': { max: 3, reverse: true },
    'coberturaProvisoes': { min: 100 },
    'pl': { min: 0, max: 15, reverse: true },
    'pVpa': { max: 2, reverse: true },
    'leveredDcf': { custom: 'aboveCurrentPrice' },
    'dividendYield': { min: 2 },
    'payoutRatio': { min: 20, max: 60 },
    'ldr': { min: 70, max: 90 },
    'beta': { min: 0.5, max: 1.5 },
  },
  consumerCyclical: {
    'pe': { min: 0, max: 22, reverse: true },
    'ps': { max: 3, reverse: true },
    'pb': { max: 3, reverse: true },
    'roe': { min: 15 },
    'margemBruta': { min: 30 },
    'margemEbitda': { min: 15 },
    'endividamento': { max: 2.5, reverse: true },
    'liquidezCorrente': { min: 1.2 },
    'rotatividadeEstoques': { min: 3 },
    'receitaCagr3y': { min: 8 },
  },
  communication: {
    'pe': { min: 0, max: 25, reverse: true },
    'ps': { max: 4, reverse: true },
    'roe': { min: 15 },
    'roic': { min: 10 },
    'margemBruta': { min: 30 },
    'margemEbitda': { min: 20 },
    'receitaCagr3y': { min: 10 },
  },
  basicMaterials: {
    'pe': { min: 0, max: 25, reverse: true },
    'pb': { max: 3, reverse: true },
    'roic': { min: 10 },
    'margemEbitda': { min: 20 },
  },
} as const;

export type ThresholdsPorSetor = typeof thresholds
export type Setor = keyof ThresholdsPorSetor
