import { Creator as CreatorType } from '../../../types/creator'

export const mockCreators: CreatorType[] = [
  {
    _id: '1',
    username: 'serriquinho',
    email: 'ser@riquinho.pt',
    firstname: 'Ser',
    lastname: 'Riquinho',
    role: 'creator',
    isPremium: true,
    topics: ['Finanças Pessoais'],
    termsAccepted: true,
    termsOfServiceAgreement: true,
    contentLicenseAgreement: true,
    paymentTermsAgreement: true,
    socialMediaLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/serriquinho' },
      { platform: 'Youtube', url: 'https://youtube.com/serriquinho' },
    ],
    profilePictureUrl: '/avatars/riquinho.jpg',
    famous: ['Youtube', 'Instagram'],
    followers: [{ userId: 'user1' }, { userId: 'user2' }],
    averageRating: 3.6,
    content: [],
    welcomeVideo: ['https://www.youtube.com/watch?v=MlhmzCb7qC8'],
    courses: [
      {
        coursesId: 'course1',
        courseName: 'O Grande Investimento',
        bannerImage: '/courses/investimento.jpg',
        purchaseLink: '#',
        timestamp: new Date().toISOString(),
      },
      {
        coursesId: 'course2',
        courseName: 'Organiza as tuas Finanças',
        bannerImage: '/courses/financas.jpg',
        purchaseLink: '#',
        timestamp: new Date().toISOString(),
      },
    ],
  },
  {
    _id: '2',
    username: 'Dra. Poupança',
    email: 'poupanca@dinheiro.pt',
    firstname: 'Maria',
    lastname: 'Poupança',
    role: 'creator',
    isPremium: false,
    topics: ['Poupança', 'Minimalismo'],
    termsAccepted: true,
    termsOfServiceAgreement: true,
    contentLicenseAgreement: true,
    paymentTermsAgreement: true,
    socialMediaLinks: [{ platform: 'Instagram', url: 'https://instagram.com/drapoupanca' }],
    profilePictureUrl: '/avatars/poupanca.jpg',
    famous: ['Instagram'],
    followers: [{ userId: 'user3' }],
    averageRating: 4.2,
    content: [],
    welcomeVideo: ['https://www.youtube.com/watch?v=Qnd9H2Kax9Y'],
    courses: [
      {
        coursesId: 'course3',
        courseName: 'Como Poupar com Estilo',
        bannerImage: '/courses/poupar.jpg',
        purchaseLink: '#',
        timestamp: new Date().toISOString(),
      },
    ],
  },
  {
    _id: '3',
    username: 'O Contabilista Zen',
    email: 'zen@financas.pt',
    firstname: 'João',
    lastname: 'Silva',
    role: 'creator',
    isPremium: true,
    topics: ['Fiscalidade', 'Mindfulness Financeiro'],
    termsAccepted: true,
    termsOfServiceAgreement: true,
    contentLicenseAgreement: true,
    paymentTermsAgreement: true,
    socialMediaLinks: [{ platform: 'Youtube', url: 'https://youtube.com/contabilistazen' }],
    profilePictureUrl: '/avatars/zen.jpg',
    famous: ['Youtube'],
    followers: [],
    averageRating: 4.8,
    content: [],
    welcomeVideo: [],
    courses: [
      {
        coursesId: 'course4',
        courseName: 'Zen e IRS',
        bannerImage: '/courses/zen.jpg',
        purchaseLink: '#',
        timestamp: new Date().toISOString(),
      },
    ],
  },
  {
    _id: '4',
    username: 'Cria e Investe',
    email: 'cria@investe.pt',
    firstname: 'Cláudia',
    lastname: 'Mendes',
    role: 'creator',
    isPremium: false,
    topics: ['Empreendedorismo', 'Investimento Imobiliário'],
    termsAccepted: true,
    termsOfServiceAgreement: true,
    contentLicenseAgreement: true,
    paymentTermsAgreement: true,
    socialMediaLinks: [{ platform: 'Instagram', url: 'https://instagram.com/criaeinveste' }],
    profilePictureUrl: '/avatars/cria.jpg',
    famous: ['Instagram'],
    followers: [{ userId: 'user4' }, { userId: 'user5' }, { userId: 'user6' }],
    averageRating: 4.0,
    content: [],
    welcomeVideo: ['https://www.youtube.com/watch?v=y6120QOlsfU'],
    courses: [
      {
        coursesId: 'course5',
        courseName: 'Como Criar um Negócio Rentável',
        bannerImage: '/courses/negocio.jpg',
        purchaseLink: '#',
        timestamp: new Date().toISOString(),
      },
    ],
  },
]
