import { ContentType, ContentCategory, PublishStatus } from '@/features/hub/types'
import { UserRole } from '@/features/auth/types'
import {
  NotificationType,
  type Notification,
  type FollowedCreator,
  type FavoriteItem,
  type ActivityFeedItem,
  type UserProfile,
  type SearchResult,
} from '../types'

// ========== FOLLOWED CREATORS ==========

export const mockFollowing: FollowedCreator[] = [
  {
    creatorId: 'creator-1',
    username: 'pedro-santos',
    name: 'Pedro Santos',
    avatar: undefined,
    bio: 'Especialista em financas pessoais e investimentos',
    followedAt: '2025-11-15T10:00:00Z',
  },
  {
    creatorId: 'creator-2',
    username: 'ana-costa',
    name: 'Ana Costa',
    avatar: undefined,
    bio: 'Criadora de conteudo sobre criptomoedas e blockchain',
    followedAt: '2025-12-01T14:00:00Z',
  },
  {
    creatorId: 'creator-3',
    username: 'miguel-ferreira',
    name: 'Miguel Ferreira',
    avatar: undefined,
    bio: 'Analista de acoes e ETFs',
    followedAt: '2026-01-05T09:00:00Z',
  },
  {
    creatorId: 'creator-4',
    username: 'sofia-mendes',
    name: 'Sofia Mendes',
    avatar: undefined,
    bio: 'Consultora financeira e educadora',
    followedAt: '2026-01-20T16:00:00Z',
  },
  {
    creatorId: 'creator-5',
    username: 'joao-silva',
    name: 'Joao Silva',
    avatar: undefined,
    bio: 'Trader e autor de livros sobre mercados financeiros',
    followedAt: '2026-02-01T11:00:00Z',
  },
]

// ========== FAVORITES ==========

export const mockFavorites: FavoriteItem[] = [
  {
    contentId: 'article-1',
    contentType: ContentType.ARTICLE,
    title: 'Como comecar a investir em 2026',
    coverImage: undefined,
    creatorName: 'Pedro Santos',
    favoritedAt: '2026-02-10T10:00:00Z',
  },
  {
    contentId: 'course-1',
    contentType: ContentType.COURSE,
    title: 'Fundamentos de Analise Tecnica',
    coverImage: undefined,
    creatorName: 'Miguel Ferreira',
    favoritedAt: '2026-02-08T14:00:00Z',
  },
  {
    contentId: 'video-1',
    contentType: ContentType.VIDEO,
    title: 'ETFs: Guia Completo para Iniciantes',
    coverImage: undefined,
    creatorName: 'Ana Costa',
    favoritedAt: '2026-02-05T09:00:00Z',
  },
  {
    contentId: 'book-1',
    contentType: ContentType.BOOK,
    title: 'O Homem Mais Rico da Babilonia',
    coverImage: 'https://m.media-amazon.com/images/I/81TR4j3QWDL._AC_UF1000,1000_QL80_.jpg',
    creatorName: 'Pedro Santos',
    favoritedAt: '2026-02-03T16:00:00Z',
  },
  {
    contentId: 'podcast-1',
    contentType: ContentType.PODCAST,
    title: 'Investir Sem Medo',
    coverImage: undefined,
    creatorName: 'Sofia Mendes',
    favoritedAt: '2026-01-28T11:00:00Z',
  },
  {
    contentId: 'article-2',
    contentType: ContentType.ARTICLE,
    title: 'Orcamento Familiar: Metodo 50/30/20',
    coverImage: undefined,
    creatorName: 'Sofia Mendes',
    favoritedAt: '2026-01-25T08:00:00Z',
  },
  {
    contentId: 'event-1',
    contentType: ContentType.EVENT,
    title: 'Workshop: Investir em ETFs',
    coverImage: undefined,
    creatorName: 'Ana Costa',
    favoritedAt: '2026-01-20T15:00:00Z',
  },
  {
    contentId: 'course-2',
    contentType: ContentType.COURSE,
    title: 'Criptomoedas do Zero ao Avancado',
    coverImage: undefined,
    creatorName: 'Ana Costa',
    favoritedAt: '2026-01-18T10:00:00Z',
  },
  {
    contentId: 'video-2',
    contentType: ContentType.VIDEO,
    title: 'Top 5 Acoes Portuguesas para 2026',
    coverImage: undefined,
    creatorName: 'Miguel Ferreira',
    favoritedAt: '2026-01-15T14:00:00Z',
  },
  {
    contentId: 'book-2',
    contentType: ContentType.BOOK,
    title: 'Pai Rico, Pai Pobre',
    coverImage: 'https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UF1000,1000_QL80_.jpg',
    creatorName: 'Pedro Santos',
    favoritedAt: '2026-01-10T09:00:00Z',
  },
]

// ========== NOTIFICATIONS ==========

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: NotificationType.NEW_CONTENT,
    title: 'Novo artigo publicado',
    message: 'Pedro Santos publicou "Estrategias de Investimento para 2026"',
    isRead: false,
    actorId: 'creator-1',
    actorName: 'Pedro Santos',
    targetType: ContentType.ARTICLE,
    targetId: 'article-new-1',
    targetUrl: '/hub/articles/estrategias-investimento-2026',
    createdAt: '2026-02-15T09:00:00Z',
  },
  {
    id: 'notif-2',
    type: NotificationType.COMMENT_REPLY,
    title: 'Nova resposta ao teu comentario',
    message: 'Ana Costa respondeu ao teu comentario em "ETFs: Guia Completo"',
    isRead: false,
    actorId: 'creator-2',
    actorName: 'Ana Costa',
    targetType: ContentType.VIDEO,
    targetId: 'video-1',
    targetUrl: '/hub/videos/etfs-guia-completo',
    createdAt: '2026-02-14T16:30:00Z',
  },
  {
    id: 'notif-3',
    type: NotificationType.LIKE_RECEIVED,
    title: 'O teu comentario recebeu um gosto',
    message: 'Miguel Ferreira gostou do teu comentario',
    isRead: false,
    actorId: 'creator-3',
    actorName: 'Miguel Ferreira',
    targetType: ContentType.COURSE,
    targetId: 'course-1',
    targetUrl: '/hub/courses/fundamentos-analise-tecnica',
    createdAt: '2026-02-14T12:00:00Z',
  },
  {
    id: 'notif-4',
    type: NotificationType.NEW_CONTENT,
    title: 'Novo curso disponivel',
    message: 'Sofia Mendes lancou o curso "Orcamento Inteligente"',
    isRead: true,
    actorId: 'creator-4',
    actorName: 'Sofia Mendes',
    targetType: ContentType.COURSE,
    targetId: 'course-new-1',
    targetUrl: '/hub/courses/orcamento-inteligente',
    createdAt: '2026-02-13T10:00:00Z',
  },
  {
    id: 'notif-5',
    type: NotificationType.FOLLOW_NEW,
    title: 'Novo seguidor',
    message: 'Joao Silva comecou a seguir-te',
    isRead: true,
    actorId: 'creator-5',
    actorName: 'Joao Silva',
    createdAt: '2026-02-12T14:00:00Z',
  },
  {
    id: 'notif-6',
    type: NotificationType.RATING_RECEIVED,
    title: 'Nova avaliacao',
    message: 'Recebeste uma avaliacao de 5 estrelas em "Analise Tecnica"',
    isRead: true,
    actorName: 'Utilizador Anonimo',
    targetType: ContentType.COURSE,
    targetId: 'course-1',
    targetUrl: '/hub/courses/fundamentos-analise-tecnica',
    createdAt: '2026-02-11T11:00:00Z',
  },
  {
    id: 'notif-7',
    type: NotificationType.SYSTEM,
    title: 'Atualizacao da plataforma',
    message: 'Novas funcionalidades sociais disponiveis! Explora o teu perfil e feed.',
    isRead: true,
    createdAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'notif-8',
    type: NotificationType.NEW_CONTENT,
    title: 'Novo podcast publicado',
    message: 'Ana Costa publicou um novo episodio de "Crypto Talks"',
    isRead: true,
    actorId: 'creator-2',
    actorName: 'Ana Costa',
    targetType: ContentType.PODCAST,
    targetId: 'podcast-2',
    targetUrl: '/hub/podcasts/crypto-talks',
    createdAt: '2026-02-09T15:00:00Z',
  },
  {
    id: 'notif-9',
    type: NotificationType.COMMENT_REPLY,
    title: 'Nova resposta',
    message: 'Pedro Santos respondeu no topico "Melhores ETFs"',
    isRead: true,
    actorId: 'creator-1',
    actorName: 'Pedro Santos',
    targetType: ContentType.ARTICLE,
    targetId: 'article-1',
    targetUrl: '/hub/articles/melhores-etfs',
    createdAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'notif-10',
    type: NotificationType.NEW_CONTENT,
    title: 'Novo evento',
    message: 'Miguel Ferreira criou "Masterclass Analise Tecnica"',
    isRead: true,
    actorId: 'creator-3',
    actorName: 'Miguel Ferreira',
    targetType: ContentType.EVENT,
    targetId: 'event-2',
    targetUrl: '/hub/lives/masterclass-analise-tecnica',
    createdAt: '2026-02-07T09:00:00Z',
  },
  {
    id: 'notif-11',
    type: NotificationType.LIKE_RECEIVED,
    title: 'Novo gosto',
    message: 'Sofia Mendes gostou da tua avaliacao',
    isRead: true,
    actorId: 'creator-4',
    actorName: 'Sofia Mendes',
    createdAt: '2026-02-06T14:00:00Z',
  },
  {
    id: 'notif-12',
    type: NotificationType.SYSTEM,
    title: 'Bem-vindo ao FinHub!',
    message: 'Comeca por explorar os conteudos e seguir os teus criadores favoritos.',
    isRead: true,
    createdAt: '2026-02-01T08:00:00Z',
  },
]

// ========== ACTIVITY FEED ==========

export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: 'activity-1',
    type: 'content_published',
    content: {
      id: 'article-new-1',
      type: ContentType.ARTICLE,
      slug: 'estrategias-investimento-2026',
      title: 'Estrategias de Investimento para 2026',
      description: 'As melhores estrategias para investir o teu dinheiro este ano.',
      creator: {
        id: 'creator-1',
        name: 'Pedro Santos',
        username: 'pedro-santos',
        email: '',
        role: UserRole.CREATOR,
        isEmailVerified: true,
        createdAt: '',
        updatedAt: '',
      },
      creatorId: 'creator-1',
      category: ContentCategory.STOCKS,
      tags: ['investimento', 'estrategia', '2026'],
      viewCount: 150,
      likeCount: 23,
      favoriteCount: 12,
      shareCount: 5,
      averageRating: 4.5,
      ratingCount: 8,
      reviewCount: 8,
      commentCount: 4,
      commentsEnabled: true,
      requiredRole: UserRole.VISITOR,
      isPremium: false,
      isFeatured: true,
      status: PublishStatus.PUBLISHED,
      isPublished: true,
      publishedAt: '2026-02-15T09:00:00Z',
      createdAt: '2026-02-14T18:00:00Z',
      updatedAt: '2026-02-15T09:00:00Z',
    },
    creatorName: 'Pedro Santos',
    createdAt: '2026-02-15T09:00:00Z',
  },
  {
    id: 'activity-2',
    type: 'content_published',
    content: {
      id: 'video-new-1',
      type: ContentType.VIDEO,
      slug: 'bitcoin-analise-fevereiro',
      title: 'Bitcoin: Analise de Fevereiro 2026',
      description: 'Analise completa do mercado de Bitcoin para este mes.',
      creator: {
        id: 'creator-2',
        name: 'Ana Costa',
        username: 'ana-costa',
        email: '',
        role: UserRole.CREATOR,
        isEmailVerified: true,
        createdAt: '',
        updatedAt: '',
      },
      creatorId: 'creator-2',
      category: ContentCategory.CRYPTO,
      tags: ['bitcoin', 'cripto', 'analise'],
      viewCount: 320,
      likeCount: 45,
      favoriteCount: 28,
      shareCount: 15,
      averageRating: 4.7,
      ratingCount: 15,
      reviewCount: 15,
      commentCount: 12,
      commentsEnabled: true,
      requiredRole: UserRole.FREE,
      isPremium: false,
      isFeatured: false,
      status: PublishStatus.PUBLISHED,
      isPublished: true,
      publishedAt: '2026-02-14T16:00:00Z',
      createdAt: '2026-02-14T12:00:00Z',
      updatedAt: '2026-02-14T16:00:00Z',
    },
    creatorName: 'Ana Costa',
    createdAt: '2026-02-14T16:00:00Z',
  },
  {
    id: 'activity-3',
    type: 'content_published',
    content: {
      id: 'course-new-1',
      type: ContentType.COURSE,
      slug: 'orcamento-inteligente',
      title: 'Orcamento Inteligente',
      description: 'Aprende a gerir o teu orcamento de forma eficiente e a poupar mais.',
      creator: {
        id: 'creator-4',
        name: 'Sofia Mendes',
        username: 'sofia-mendes',
        email: '',
        role: UserRole.CREATOR,
        isEmailVerified: true,
        createdAt: '',
        updatedAt: '',
      },
      creatorId: 'creator-4',
      category: ContentCategory.BUDGETING,
      tags: ['orcamento', 'poupanca', 'financas-pessoais'],
      viewCount: 89,
      likeCount: 18,
      favoriteCount: 10,
      shareCount: 3,
      averageRating: 4.9,
      ratingCount: 5,
      reviewCount: 5,
      commentCount: 2,
      commentsEnabled: true,
      requiredRole: UserRole.FREE,
      isPremium: false,
      isFeatured: true,
      status: PublishStatus.PUBLISHED,
      isPublished: true,
      publishedAt: '2026-02-13T10:00:00Z',
      createdAt: '2026-02-12T20:00:00Z',
      updatedAt: '2026-02-13T10:00:00Z',
    },
    creatorName: 'Sofia Mendes',
    createdAt: '2026-02-13T10:00:00Z',
  },
  {
    id: 'activity-4',
    type: 'content_updated',
    content: {
      id: 'course-1',
      type: ContentType.COURSE,
      slug: 'fundamentos-analise-tecnica',
      title: 'Fundamentos de Analise Tecnica - Atualizado!',
      description: 'Novo modulo adicionado: Indicadores de Volume.',
      creator: {
        id: 'creator-3',
        name: 'Miguel Ferreira',
        username: 'miguel-ferreira',
        email: '',
        role: UserRole.CREATOR,
        isEmailVerified: true,
        createdAt: '',
        updatedAt: '',
      },
      creatorId: 'creator-3',
      category: ContentCategory.STOCKS,
      tags: ['analise-tecnica', 'trading', 'indicadores'],
      viewCount: 540,
      likeCount: 67,
      favoriteCount: 42,
      shareCount: 20,
      averageRating: 4.6,
      ratingCount: 28,
      reviewCount: 28,
      commentCount: 18,
      commentsEnabled: true,
      requiredRole: UserRole.PREMIUM,
      isPremium: true,
      isFeatured: true,
      status: PublishStatus.PUBLISHED,
      isPublished: true,
      publishedAt: '2025-10-01T10:00:00Z',
      createdAt: '2025-09-15T14:00:00Z',
      updatedAt: '2026-02-12T15:00:00Z',
    },
    creatorName: 'Miguel Ferreira',
    createdAt: '2026-02-12T15:00:00Z',
  },
  {
    id: 'activity-5',
    type: 'creator_announcement',
    content: {
      id: 'podcast-ep-new',
      type: ContentType.PODCAST,
      slug: 'investir-sem-medo-ep-10',
      title: 'Investir Sem Medo - Ep. 10: Impostos e Investimentos',
      description: 'Tudo o que precisas saber sobre tributacao de investimentos em Portugal.',
      creator: {
        id: 'creator-4',
        name: 'Sofia Mendes',
        username: 'sofia-mendes',
        email: '',
        role: UserRole.CREATOR,
        isEmailVerified: true,
        createdAt: '',
        updatedAt: '',
      },
      creatorId: 'creator-4',
      category: ContentCategory.PERSONAL_FINANCE,
      tags: ['impostos', 'investimento', 'portugal'],
      viewCount: 200,
      likeCount: 35,
      favoriteCount: 22,
      shareCount: 10,
      averageRating: 4.8,
      ratingCount: 12,
      reviewCount: 12,
      commentCount: 8,
      commentsEnabled: true,
      requiredRole: UserRole.VISITOR,
      isPremium: false,
      isFeatured: false,
      status: PublishStatus.PUBLISHED,
      isPublished: true,
      publishedAt: '2026-02-11T08:00:00Z',
      createdAt: '2026-02-10T22:00:00Z',
      updatedAt: '2026-02-11T08:00:00Z',
    },
    creatorName: 'Sofia Mendes',
    createdAt: '2026-02-11T08:00:00Z',
  },
]

// ========== USER PROFILES ==========

export const mockUserProfiles: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Rui',
    lastName: 'Oliveira',
    email: 'rui@example.com',
    username: 'rui-oliveira',
    bio: 'Entusiasta de financas pessoais e investidor amador',
    role: UserRole.FREE,
    isEmailVerified: true,
    favoriteTopics: ['investimentos', 'poupanca', 'etfs'],
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
    followingCount: 5,
    favoritesCount: 10,
    commentsCount: 23,
    ratingsCount: 8,
    joinedAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Maria',
    lastName: 'Silva',
    email: 'maria@example.com',
    username: 'maria-silva',
    bio: 'A aprender sobre investimentos e liberdade financeira',
    role: UserRole.PREMIUM,
    isEmailVerified: true,
    favoriteTopics: ['cripto', 'acoes', 'liberdade-financeira'],
    createdAt: '2025-08-15T14:00:00Z',
    updatedAt: '2026-02-12T09:00:00Z',
    followingCount: 8,
    favoritesCount: 15,
    commentsCount: 42,
    ratingsCount: 12,
    joinedAt: '2025-08-15T14:00:00Z',
  },
]

// ========== SEARCH RESULTS ==========

export const mockSearchResults: SearchResult[] = [
  {
    id: 'article-1',
    type: ContentType.ARTICLE,
    title: 'Como comecar a investir em 2026',
    description: 'Guia completo para iniciantes no mundo dos investimentos.',
    url: '/hub/articles/como-comecar-investir-2026',
    score: 0.95,
  },
  {
    id: 'course-1',
    type: ContentType.COURSE,
    title: 'Fundamentos de Analise Tecnica',
    description: 'Curso completo sobre analise tecnica de acoes.',
    url: '/hub/courses/fundamentos-analise-tecnica',
    score: 0.88,
  },
  {
    id: 'video-1',
    type: ContentType.VIDEO,
    title: 'ETFs: Guia Completo para Iniciantes',
    description: 'Tudo o que precisas saber sobre ETFs.',
    url: '/hub/videos/etfs-guia-completo',
    score: 0.82,
  },
  {
    id: 'creator-1',
    type: 'creator',
    title: 'Pedro Santos',
    description: 'Especialista em financas pessoais e investimentos',
    url: '/creators/pedro-santos',
    score: 0.78,
  },
  {
    id: 'book-1',
    type: ContentType.BOOK,
    title: 'O Homem Mais Rico da Babilonia',
    description: 'Principios financeiros antigos que continuam a guiar milhoes.',
    coverImage: 'https://m.media-amazon.com/images/I/81TR4j3QWDL._AC_UF1000,1000_QL80_.jpg',
    url: '/hub/books/o-homem-mais-rico-da-babilonia',
    score: 0.75,
  },
  {
    id: 'podcast-1',
    type: ContentType.PODCAST,
    title: 'Investir Sem Medo',
    description: 'Podcast semanal sobre investimentos para todos.',
    url: '/hub/podcasts/investir-sem-medo',
    score: 0.72,
  },
  {
    id: 'event-1',
    type: ContentType.EVENT,
    title: 'Workshop: Investir em ETFs',
    description: 'Workshop online gratuito sobre ETFs.',
    url: '/hub/lives/workshop-investir-etfs',
    score: 0.68,
  },
]
